name: workout_rumah
description: Personal workout companion untuk latihan di rumah.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Memaksa aset font disertakan ke dalam bundle output web
  assets:
    - assets/fonts/

  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/dm_serif_display_regular.ttf
