name: workout_rumah
description: Personal workout companion untuk latihan di rumah.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/waves.frag

  # Memaksa aset font disertakan ke dalam bundle output web
  assets:
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi_regular.otf
        - asset: assets/fonts/satoshi_light.otf
          weight: 300
        - asset: assets/fonts/satoshi_medium.otf
          weight: 500
        - asset: assets/fonts/satoshi_bold.otf
          weight: 700
        - asset: assets/fonts/satoshi_black.otf
          weight: 900
        - asset: assets/fonts/satoshi_italic.otf
          style: italic
        - asset: assets/fonts/satoshi_light_italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/satoshi_medium_italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/satoshi_bold_italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/satoshi_black_italic.otf
          weight: 900
          style: italic
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/dm_serif_display_regular.ttf
